from Admins                 import Admins
from DepartmentActivitySphere import DepartmentActivitySphere
from Department             import Department
from DetailCategory         import DetailCategory
from DetailModel            import DetailModel
from EmployeeRole           import EmployeeRole
from Employee               import Employee
from EmployeeOperationType  import EmployeeOperationType
from EmployeeOperation      import EmployeeOperation
from EquipmentCategory      import EquipmentCategory
from EquipmentModel         import EquipmentModel
from Equipment              import Equipment
from EquipmentOperationType import EquipmentOperationType
from EquipmentOperation     import EquipmentOperation
from EquipmentOwner         import EquipmentOwner
from TaskPriority           import TaskPriority
from Task                   import Task
from Repair                 import Repair
from TaskState              import TaskState
from TaskOperation          import TaskOperation
from Technics               import Technics

from special import StatisticsByTechnic