# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Fri Dec 21 12:45:03 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 630)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.employeeListTab = QtGui.QGroupBox(self.centralWidget)
        self.employeeListTab.setObjectName("employeeListTab")
        self.gridLayout_2 = QtGui.QGridLayout(self.employeeListTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.employeeListBackButton = QtGui.QPushButton(self.employeeListTab)
        self.employeeListBackButton.setObjectName("employeeListBackButton")
        self.horizontalLayout_2.addWidget(self.employeeListBackButton)
        self.label = QtGui.QLabel(self.employeeListTab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.employeeListPageIndicator = QtGui.QLabel(self.employeeListTab)
        self.employeeListPageIndicator.setObjectName("employeeListPageIndicator")
        self.horizontalLayout_2.addWidget(self.employeeListPageIndicator)
        self.employeeListForwardButton = QtGui.QPushButton(self.employeeListTab)
        self.employeeListForwardButton.setObjectName("employeeListForwardButton")
        self.horizontalLayout_2.addWidget(self.employeeListForwardButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.employeeListTable = QtGui.QTableWidget(self.employeeListTab)
        self.employeeListTable.setMidLineWidth(-15)
        self.employeeListTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.employeeListTable.setRowCount(1)
        self.employeeListTable.setColumnCount(2)
        self.employeeListTable.setObjectName("employeeListTable")
        self.employeeListTable.setColumnCount(2)
        self.employeeListTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.employeeListTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.employeeListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.employeeListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.employeeListTable.setItem(0, 0, item)
        self.verticalLayout.addWidget(self.employeeListTable)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.employeeListTab)
        self.employeeInfoTab = QtGui.QGroupBox(self.centralWidget)
        self.employeeInfoTab.setObjectName("employeeInfoTab")
        self.gridLayout_3 = QtGui.QGridLayout(self.employeeInfoTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.employeeInfoTab)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.tab_1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtGui.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.tab_1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.tab_1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.tab_1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 443, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.employeeInfoTab)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Лабораторная работа №3", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListTab.setTitle(QtGui.QApplication.translate("MainWindow", "Список сотрудников", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListBackButton.setText(QtGui.QApplication.translate("MainWindow", "Назад", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Отображается страница: ", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListPageIndicator.setText(QtGui.QApplication.translate("MainWindow", "## из ##", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListForwardButton.setText(QtGui.QApplication.translate("MainWindow", "Вперёд", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListTable.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "ыыы", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "СНИЛС", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "ФИО", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.employeeListTable.isSortingEnabled()
        self.employeeListTable.setSortingEnabled(False)
        self.employeeListTable.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "as", None, QtGui.QApplication.UnicodeUTF8))
        self.employeeListTable.setSortingEnabled(__sortingEnabled)
        self.employeeInfoTab.setTitle(QtGui.QApplication.translate("MainWindow", "Информация о сотруднике", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Полное имя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "СНИЛС", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Логин", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Телефон", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Адрес", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Должность", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Анкета", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Список операций", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Оборудование и задачи", None, QtGui.QApplication.UnicodeUTF8))

